language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


# jar 파일을 s3에 올릴수있게 설정
before_deploy:
  - zip -r pray-for-refrigerator *
  - mkdir -p deploy
  - mv pray-for-refrigerator.zip deploy/pray-for-refrigerator.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된값

    bucket: refrigerator-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된값

    bucket: refrigerator-springboot-build #S3 버킷
    key: pray-for-refrigerator.zip #빌드 파일을 압축해서 전달
    bundle_type: zip #압축 확장자
    application: pray-for-refrigerator #웹 콘솔에서 등록한 CodeDeploy애플리케이션
    deployment_group: pray-for-refrigerator-deployment-group # CodeDeploy 배포그룹
    region: ap-northeast-2
    local_dir: deploy # before_deploy에서 생성한 디렉토리


# CI 실행시 메일로 알람
notifications:
  email:
    recipients:
      - blackmilk274@gmail.com
