version: 0.0 #codedeploy version
os: linux
files:
  - source: / #codedeploy에서 준 파일 중 destination으로 옮길 대상
#    destination: /home/ec2-user/app/step2/zip/ #파일을 받을 위치
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

# codeDeploy 에서 ec2서버로 넘겨준 파일들 권한
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어
hooks:
  AfterInstall:
    - location: stop.sh #nginx와 연결되어 있지 않은 스프링 부트 종료
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh #nginx와 연결되어있지 않은 port로 새 버전 부트 시작
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh #새 스프링부트가 정상실행 되었는지 확인
      timeout: 60
      runas: ec2-user

